import os, sys, imaplib, smtplib, email, re
from email.message import EmailMessage
from email.header import decode_header
from datetime import datetime

GMAIL_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".gmail")
PASSWORD_FILE = os.path.join(GMAIL_DIR, "app-password")
EMAIL_ADDR = os.environ.get("GIT_EMAIL", "worldshaans@gmail.com")

CODING_KEYWORDS = [
    "github", "gitlab", "pull request", "pr", "review", "issue",
    "commit", "deploy", "ci", "pipeline", "workflow", "merge",
    "code review", "assignment", "@you", "mentioned you",
]


def _get_password():
    if not os.path.exists(PASSWORD_FILE):
        print("ERROR: App password not found at " + PASSWORD_FILE)
        sys.exit(1)
    with open(PASSWORD_FILE) as f:
        return f.read().strip()


def send_email(to, subject, body):
    password = _get_password()
    msg = EmailMessage()
    msg.set_content(body)
    msg["To"] = to
    msg["From"] = EMAIL_ADDR
    msg["Subject"] = subject

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(EMAIL_ADDR, password)
            server.send_message(msg)
        print(f"Email sent: {subject}")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False


def read_coding_emails(max_results=10):
    password = _get_password()
    items = []

    try:
        mail = imaplib.IMAP4_SSL("imap.gmail.com")
        mail.login(EMAIL_ADDR, password)
        mail.select("INBOX")

        query_parts = [f'OR OR OR OR OR OR OR OR OR OR']
        query_parts = []
        for kw in CODING_KEYWORDS:
            query_parts.append(f'(SUBJECT "{kw}")')
            query_parts.append(f'(BODY "{kw}")')
        query = " ".join(f"OR {query_parts[i]} {query_parts[i+1]}" if i + 1 < len(query_parts) else query_parts[i] for i in range(0, len(query_parts), 2))
        query = f"({'OR '.join(query_parts)})" if len(query_parts) == 2 else f"({query_parts[0]})"
        if len(query_parts) > 2:
            combined = query_parts[0]
            for part in query_parts[1:]:
                combined = f"OR {combined} {part}"
            query = combined

        result, data = mail.search(None, query)

        if result == "OK" and data[0]:
            ids = data[0].split()
            recent_ids = ids[-max_results:]

            for mid in recent_ids:
                result, msg_data = mail.fetch(mid, "(BODY.PEEK[HEADER.FIELDS (FROM SUBJECT DATE)])")
                if result != "OK" or not msg_data or not msg_data[0]:
                    continue
                raw = msg_data[0][1].decode("utf-8", errors="replace")
                parsed = email.message_from_string(raw)
                items.append({
                    "from": parsed.get("From", ""),
                    "subject": parsed.get("Subject", ""),
                    "date": parsed.get("Date", ""),
                })

        mail.logout()

    except Exception as e:
        print(f"Failed to read emails: {e}")

    return items


def send_daily_summary(stars, contribs, streak, repos, followers, commits, prs, issues, reviews, heartbeat_info, astro_info=None):
    to = EMAIL_ADDR
    date_str = datetime.now().strftime("%Y-%m-%d")
    subject = f"Pipeline Report \u2014 {date_str}"

    astro_section = ""
    if astro_info:
        astro_section = f"""
Astro Tasks
{astro_info}
"""

    body = f"""Daily Pipeline Report
{date_str}

GitHub Stats
  Stars: {stars}
  Contributions: {contribs}
  Streak: {streak} days
  Public Repos: {repos}
  Followers: {followers}

Contributions Breakdown
  Commits: {commits}
  Pull Requests: {prs}
  Issues: {issues}
  Reviews: {reviews}

Heartbeat Summary
{heartbeat_info}
{astro_section}\u2014 Generated by pipeline.sh
"""

    return send_email(to, subject, body)
